#!/bin/bash
#Initialize working tree temporary dir
gitworkdir=`mktemp -d --suffix=gitworktree`

#Lets parse the git ref and get our branch name
while read oldrev newrev ref
do
    branch_ref="$ref"
done
branch=`echo "$branch_ref" | sed 's/.*\///'`

#Get a list of changed files, by default yaml and pp
git_check=`git log $branch --oneline --name-only --max-count=1 HEAD  | egrep -x '.*.pp|.*.yaml|.*.yml'`

#Create our working tree
git worktree add -f $gitworkdir $branch

#Run puppet-lint, parser to check syntax for puppet modules - Should add support for .erb
for X in $git_check;do puppet-lint $gitworkdir/$X;done
for Y in $git_check;do if [[ ${Y} =~ .*.pp ]];then puppet parser validate $gitworkdir/$Y;fi;done

#Cleanup our mess
rm -rf $gitworkdir
git worktree prune
